# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-09 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0004_remove_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('deal', models.CharField(max_length=200)),
                ('shop', models.CharField(max_length=200)),
            ],
        ),
    ]
